version: "3"
services:
  mssql:
    image: microsoft/mssql-server-2016-express-windows:latest
    ports:
    - "1433:1433"
    environment:
    - sa_password=7?107=uoVzejpVeIN39
  # voting:
  #   build:
  #     context: "./src/"
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - mssql
  #   links:
  #     - mssql
  # result:
  #   build:
  #     context: "./result/"
  #   environment:
  #     - VOTE_SERVICE_URL=http://voting./v1/voting/
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - voting
networks:
  default:
    external:
      name: nat
